// routes/shippingRateRoutes.ts
import { Router } from 'express'
import {
  cancelDeliveryOneShipmentController,
  calculateDeliveryOneShippingCostController,
  checkDeliveryOnePincodeServiceabilityController,
  createDeliveryOnePickupRequestController,
  createDeliveryOneShipmentController,
  createDeliveryOneWarehouseController,
  downloadDeliveryOneDocumentController,
  editDeliveryOneShipmentController,
  fetchDeliveryOneWaybillsController,
  generateDeliveryOneLabelController,
  getCourierCredentialsController,
  getDeliveryOneExpectedTatController,
  getDeliveryOneNdrStatusController,
  deleteShippingRateController,
  fetchAvailableCouriersForAdmin,
  getAllCouriersController,
  getShippingRatesController,
  importShippingRatesController,
  submitDeliveryOneNdrActionController,
  trackDeliveryOneShipmentController,
  updateDeliveryOneCredentialsController,
  updateDeliveryOneEWaybillController,
  updateDeliveryOneWarehouseController,
  updateXpressbeesCredentialsController,
  updateShippingRateController,
} from '../../controllers/admin/courier.controller'
import { isAdminMiddleware } from '../../middlewares/isAdmin'
import { requireAuth } from '../../middlewares/requireAuth'
import { upload } from '../../middlewares/upload'

const router = Router()

router.get('/shipping-rates', getShippingRatesController)
router.get('/list', getAllCouriersController)

router.put(
  '/shipping-rate/:id/:planId',
  requireAuth,
  isAdminMiddleware,
  updateShippingRateController,
)
router.post(
  '/shipping-rates/import',
  requireAuth,
  isAdminMiddleware,
  upload.single('file'),
  importShippingRatesController,
)
router.post('/available', requireAuth, fetchAvailableCouriersForAdmin)
router.get('/credentials', requireAuth, isAdminMiddleware, getCourierCredentialsController)
router.put(
  '/credentials/delivery-one',
  requireAuth,
  isAdminMiddleware,
  updateDeliveryOneCredentialsController,
)
router.put(
  '/credentials/xpressbees',
  requireAuth,
  isAdminMiddleware,
  updateXpressbeesCredentialsController,
)
router.get(
  '/delivery-one/waybills',
  requireAuth,
  isAdminMiddleware,
  fetchDeliveryOneWaybillsController,
)
router.post(
  '/delivery-one/waybills',
  requireAuth,
  isAdminMiddleware,
  fetchDeliveryOneWaybillsController,
)
router.get(
  '/delivery-one/pincode-serviceability',
  requireAuth,
  isAdminMiddleware,
  checkDeliveryOnePincodeServiceabilityController,
)
router.post(
  '/delivery-one/pincode-serviceability',
  requireAuth,
  isAdminMiddleware,
  checkDeliveryOnePincodeServiceabilityController,
)
router.get(
  '/delivery-one/pincodes/:pincode/serviceability',
  requireAuth,
  isAdminMiddleware,
  checkDeliveryOnePincodeServiceabilityController,
)
router.get(
  '/delivery-one/shipping-cost',
  requireAuth,
  isAdminMiddleware,
  calculateDeliveryOneShippingCostController,
)
router.post(
  '/delivery-one/shipping-cost',
  requireAuth,
  isAdminMiddleware,
  calculateDeliveryOneShippingCostController,
)
router.get(
  '/delivery-one/expected-tat',
  requireAuth,
  isAdminMiddleware,
  getDeliveryOneExpectedTatController,
)
router.post(
  '/delivery-one/expected-tat',
  requireAuth,
  isAdminMiddleware,
  getDeliveryOneExpectedTatController,
)
router.get(
  '/delivery-one/labels',
  requireAuth,
  isAdminMiddleware,
  generateDeliveryOneLabelController,
)
router.post(
  '/delivery-one/labels',
  requireAuth,
  isAdminMiddleware,
  generateDeliveryOneLabelController,
)
router.post(
  '/delivery-one/pickups',
  requireAuth,
  isAdminMiddleware,
  createDeliveryOnePickupRequestController,
)
router.post(
  '/delivery-one/pickup-request',
  requireAuth,
  isAdminMiddleware,
  createDeliveryOnePickupRequestController,
)
router.post(
  '/delivery-one/warehouses',
  requireAuth,
  isAdminMiddleware,
  createDeliveryOneWarehouseController,
)
router.post(
  '/delivery-one/client-warehouses',
  requireAuth,
  isAdminMiddleware,
  createDeliveryOneWarehouseController,
)
router.post(
  '/delivery-one/warehouses/edit',
  requireAuth,
  isAdminMiddleware,
  updateDeliveryOneWarehouseController,
)
router.patch(
  '/delivery-one/warehouses/:name',
  requireAuth,
  isAdminMiddleware,
  updateDeliveryOneWarehouseController,
)
router.post(
  '/delivery-one/client-warehouses/edit',
  requireAuth,
  isAdminMiddleware,
  updateDeliveryOneWarehouseController,
)
router.patch(
  '/delivery-one/client-warehouses/:name',
  requireAuth,
  isAdminMiddleware,
  updateDeliveryOneWarehouseController,
)
router.post(
  '/delivery-one/shipments',
  requireAuth,
  isAdminMiddleware,
  createDeliveryOneShipmentController,
)
router.post(
  '/delivery-one/shipments/edit',
  requireAuth,
  isAdminMiddleware,
  editDeliveryOneShipmentController,
)
router.patch(
  '/delivery-one/shipments/:waybill',
  requireAuth,
  isAdminMiddleware,
  (req, res) => {
    req.body = { ...(req.body || {}), waybill: req.params.waybill }
    return editDeliveryOneShipmentController(req, res)
  },
)
router.post(
  '/delivery-one/shipments/cancel',
  requireAuth,
  isAdminMiddleware,
  cancelDeliveryOneShipmentController,
)
router.post(
  '/delivery-one/shipments/:waybill/cancel',
  requireAuth,
  isAdminMiddleware,
  cancelDeliveryOneShipmentController,
)
router.post(
  '/delivery-one/shipments/ewaybill',
  requireAuth,
  isAdminMiddleware,
  updateDeliveryOneEWaybillController,
)
router.put(
  '/delivery-one/shipments/:waybill/ewaybill',
  requireAuth,
  isAdminMiddleware,
  updateDeliveryOneEWaybillController,
)
router.get(
  '/delivery-one/documents',
  requireAuth,
  isAdminMiddleware,
  downloadDeliveryOneDocumentController,
)
router.post(
  '/delivery-one/documents',
  requireAuth,
  isAdminMiddleware,
  downloadDeliveryOneDocumentController,
)
router.get(
  '/delivery-one/shipments/:waybill/document',
  requireAuth,
  isAdminMiddleware,
  downloadDeliveryOneDocumentController,
)
router.post(
  '/delivery-one/ndr',
  requireAuth,
  isAdminMiddleware,
  submitDeliveryOneNdrActionController,
)
router.get(
  '/delivery-one/ndr/status',
  requireAuth,
  isAdminMiddleware,
  getDeliveryOneNdrStatusController,
)
router.get(
  '/delivery-one/ndr/:uplId/status',
  requireAuth,
  isAdminMiddleware,
  getDeliveryOneNdrStatusController,
)
router.get(
  '/delivery-one/shipments/track',
  requireAuth,
  isAdminMiddleware,
  trackDeliveryOneShipmentController,
)
router.post(
  '/delivery-one/shipments/track',
  requireAuth,
  isAdminMiddleware,
  trackDeliveryOneShipmentController,
)
router.get(
  '/delivery-one/shipments/:waybill/track',
  requireAuth,
  isAdminMiddleware,
  trackDeliveryOneShipmentController,
)
router.get(
  '/delivery-one/shipments/:waybill/label',
  requireAuth,
  isAdminMiddleware,
  generateDeliveryOneLabelController,
)
router.delete(
  '/shipping-rates/:planId/:id',
  requireAuth,
  isAdminMiddleware,
  deleteShippingRateController,
)

export default router
